HW2: LinearAllocator
x-sile/made_2019_cpp pull request #1
Opened 2019-10-20 12:57 UTC by x-sile

2019-10-21 09:34 UTC, smirnov-vs requested changes

2019-10-21 09:34 UTC, smirnov-vs commented on 02/allocator.cpp
> +    head_block_ptr = (char *) malloc(maxSize);
что если память не выделена?

2019-10-21 17:59 UTC, x-sile commented on 02/allocator.cpp
> +    head_block_ptr = (char *) malloc(maxSize);
да, думал сразу добавить проверку, но поленился
сейчас добавил + тест

2019-10-22 09:32 UTC, smirnov-vs approved these changes

2019-10-22 09:47 UTC, merged