hw4
x-sile/made_2019_cpp pull request #3
Opened 2019-11-05 00:14 UTC by x-sile

2019-11-05 18:02 UTC, smirnov-vs requested changes

2019-11-05 18:02 UTC, smirnov-vs commented on 04/matrix.h
> +    int *arr;
Обычно индексы идут как size_t

2019-11-05 18:02 UTC, smirnov-vs commented on 04/matrix.h
> +        int &operator[](int col) const;
Хак, в лекции есть все, чтобы его избежать

2019-11-06 17:58 UTC, x-sile commented on 04/matrix.h
> +        int &operator[](int col) const;
сделал 2 метода, как в лекции

2019-11-11 17:35 UTC, x-sile commented on 04/matrix.h
> +    int *arr;
исправил

2019-11-12 10:07 UTC, smirnov-vs requested changes
константную матрицу можно отредактировать
чтобы такого не происходило код надо внимательно тестировать, придумать побольше кейсов

2019-11-18 08:36 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-11-19 08:46 UTC, merged