hw7
x-sile/made_2019_cpp pull request #6
Opened 2019-11-21 21:31 UTC by x-sile

2019-11-24 11:00 UTC, smirnov-vs requested changes

2019-11-24 11:00 UTC, smirnov-vs commented on 07/string_format.h
> +    std::stringstream stream;
выгоднее наполнять std::string, чем медленный поток

2019-11-24 11:00 UTC, smirnov-vs commented on 07/string_format.h
> +std::string process(const char *str, const std::vector<std::string> &arr) {
могут быть ошибки линковки

2019-11-26 14:41 UTC, smirnov-vs commented
что насчет линковки? будут несколько определений функции

2019-11-26 18:47 UTC, x-sile commented on 07/string_format.h
> +std::string process(const char *str, const std::vector<std::string> &arr) {
Честно, не понимаю, в чем могут быть ошибки=)
Где-то в стандартной либе определена функция с такой же сигнатурой?

2019-11-27 19:36 UTC, smirnov-vs approved these changes
все окей

2019-11-27 20:00 UTC, merged