hw8
x-sile/made_2019_cpp pull request #7
Opened 2019-12-01 19:25 UTC by x-sile

2019-12-02 17:13 UTC, smirnov-vs requested changes
привет!
надо пофиксить проблемы с оператором копирования

2019-12-02 17:13 UTC, smirnov-vs commented on 08/vector.h
> +template<class T, class Alloc = std::allocator<T>>
нет реализации аллокатора

2019-12-02 17:13 UTC, smirnov-vs commented on 08/vector.h
> +        std::fill(data_, data_ + size_, defaultValue);
слева мусор, в общем случае, это ub

2019-12-02 17:13 UTC, smirnov-vs commented on 08/vector.h
> +            data_[i++] = *current++;
аналогично

2019-12-02 18:31 UTC, x-sile commented on 08/vector.h
> +        std::fill(data_, data_ + size_, defaultValue);
в data_ ?
я же конструирую там дефолтные объекты

2019-12-02 18:32 UTC, x-sile commented on 08/vector.h
> +template<class T, class Alloc = std::allocator<T>>
максим на лекции говорил, что можно заиспользовать стандартный, но ок

2019-12-11 21:43 UTC, smirnov-vs commented on 08/vector.h
> +        std::fill(data_, data_ + size_, defaultValue);
да, но как переделал в любом случае лучше

2019-12-11 21:44 UTC, smirnov-vs commented on 08/vector.h
> +        std::copy(copied.data_, copied.data_ + size_, data_);
а тут?

2019-12-11 21:44 UTC, smirnov-vs commented on 08/vector.h
> +        data_ = nullptr;
что-то нигде нет деструкторов

2019-12-16 15:36 UTC, smirnov-vs approved these changes
привет!
я зачел

2019-12-16 15:36 UTC, smirnov-vs commented on 08/vector.h
> +        for (size_t i = 0; i < count; i++) {
конструировать надо только по требованию, остальная память про запас

2019-12-25 17:23 UTC, merged